//
//  clientTest.h
//  socket-cs-Demo
//
//  Created by codew on 2018/3/25.
//  Copyright © 2018年 codew. All rights reserved.
//

#ifndef clientTest_h
#define clientTest_h

#include <stdio.h>

#endif /* clientTest_h */


#include <syslog.h>
int main(int argc, char **argv)
{
    openlog("MyLog", LOG_CONS | LOG_PID, LOG_LOCAL2);
    syslog(LOG_INFO,"Thissdasdasdasdasdasdas is a syslog test message generated by program\n");
    closelog();
    return 0;
}
